### ISSUE TITLE
Error message after startup

### ISSUE THREAD

**Issue by x3rAx** [catdad/unofficial-hipchat#12]
Hi, when I start the "Unofficial HipCaht" client, I see the loading screen for a few seconds, then I'm getting this error:

> Oops, this has been up for a while. You should consider the following:
> - ...
> - In rare cases, you might find it useful to just [close this loader](#).

When I click the 'close this loader' link, the loading screen with the error message disappears and I can use HipChat as usual.

At my company we are using a personal HipChat server and I had no issues using "Unofficial HipChat" with it. Now for about two weeks I keep getting this error message every time I start the app.

I have already tried to remove the app from Chrome and add it again, but with no success.

System info:
- OS: elementary OS (v0.3.2)
- Chrome: Version 50.0.2661.102 (64-bit)

**Comment by catdad** [comment]
I am not too familiar with HipChat server. Do you know if you configure it with a hostname, and it will use all the same URLs as the HipChat online offering, or can you also configure custom routes? If you are not sure, can you tell me what the logong and chat URLs are for your server (if you'd like, change the hostname to example.com, so you are not posting your private hostname here).

Also, I have to assume you know how, since you are on GitHub... can you open up devtools and tell me if you see anything funny looking in there?

**Comment by x3rAx** [comment]
I don't know why, but now it works again.

I opened the devtools for the main.html (no errors in console so far), closed the App, opened it again (devtools opened and again no errors in console) and it just worked. Closed the devtools, restarted app, restarted browser, restartet PC... It just works :)

By the way, thanks for your great work, I had the exact same issues as you describe them in your README (except I'm on Linux but also HDPI).

Is there any way to spend you a beer (PayPal, Bitcon, etc.)?

**Comment by catdad** [comment]
Sorry we couldn't get to the bottom of this.

Thanks for your support. And yeah, this app is a huge hack, but it's not too hard to do better than the official app. Let me know if you find any other issues.
