### ISSUE TITLE
Login gets stuck in loop failing captcha.

### ISSUE THREAD

**Issue by dddaaammmooo** [catdad/unofficial-hipchat#18]
Cannot manually login either as the application keeps attempting to automatically populate the username/password every few seconds.

![image](https://cloud.githubusercontent.com/assets/4394695/25462828/15a695b0-2b35-11e7-9a57-5b31dd8a1ccc.png)

**Comment by catdad** [comment]
Yeah, I noticed that too. The captcha was added today. I don't have time to fix this any time soon, nor really care to since Chrome is discontinuing packaged apps soon. If you want to contribute, please feel free.

By the way, you actually can log in manually if you remove your account. You can do that from the little account button on the top right. Of course, it will be just as broken the next time you log in anyway, so not a great solution.

**Comment by catdad** [comment]
It appears that the captcha is gone today (it looks like a lot of people complained that selecting 37 images of mountains is insanely annoying), and login works again. @dddaaammmooo and @stalet, can either of you confirm this?

**Comment by stalet** [comment]
Yeah, it works now!
